// Every string of the news «Календарь» in the three interface languages.
// Event types are the server's (calendar_events.py); their order here is the
// order of the filter chips and the legend.
export const EVENT_TYPES = ["meeting", "dividend", "report", "fact", "notice", "listing"];

export const NEWSCAL_TX = {
  ru: {
    views: { month: "Месяц", week: "Неделя", list: "Список" },
    today: "Сегодня",
    prev: "Назад",
    next: "Вперёд",
    weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
    types: {
      meeting: "Собрания",
      dividend: "Дивиденды",
      report: "Отчётность",
      fact: "Существенные факты",
      notice: "Объявления",
      listing: "Листинг",
    },
    typeOne: {
      meeting: "Собрание акционеров",
      dividend: "Дивиденды",
      report: "Финансовая отчётность",
      fact: "Существенный факт",
      notice: "Объявление о собрании",
      listing: "Листинг",
    },
    divKinds: { decision: "Решение о дивидендах", payment_start: "Начало выплаты", payment_end: "Окончание выплаты" },
    bondKinds: { decision: "Решение о выплате дохода", payment_start: "Начало выплаты дохода", payment_end: "Окончание выплаты дохода" },
    divClasses: { ordinary: "Простые акции", preferred: "Привилегированные", bond: "Облигации" },
    allTypes: "Все типы",
    companyPh: "Компания или тикер…",
    from: "С",
    to: "по",
    resetFilters: "Сбросить фильтры",
    upcoming: "Ближайшие события",
    upcomingEmpty: "В ближайшие 60 дней заявленных событий нет.",
    inDays: (n) => (n === 0 ? "сегодня" : n === 1 ? "завтра" : `через ${n} ${plural(n, "день", "дня", "дней")}`),
    daysAgo: (n) => (n === 1 ? "вчера" : `${n} ${plural(n, "день", "дня", "дней")} назад`),
    loading: "Загружаем календарь…",
    error: "Не удалось загрузить календарь.",
    partial: "Часть источников сейчас недоступна — показаны остальные.",
    empty: "За этот период событий нет.",
    emptyFiltered: "Нет событий под выбранные фильтры.",
    more: (n) => `ещё ${n}`,
    dayEvents: (n) => `${n} ${plural(n, "событие", "события", "событий")}`,
    wholePeriod: "Весь период",
    download: "Скачать CSV",
    close: "Закрыть",
    upcomingTag: "Предстоит",
    pastTag: "Прошло",
    todayTag: "Сегодня",
    noticeFor: (d) => `Созыв собрания на ${d}`,
    reportTitle: (form, period) => `Отчёт ${form}${period ? ` за ${period}` : ""}`.trim(),
    listingTitle: (kind) => `Допуск к торгам: ${kind}`,
    shareTypes: { ordinary: "простые акции", preferred: "привилегированные акции", bond: "облигации" },
    d: {
      company: "Компания",
      ticker: "Тикер",
      date: "Дата",
      time: "Время",
      type: "Тип события",
      decision: "Дата решения",
      published: "Опубликовано",
      meeting: "Дата собрания",
      cls: "Бумага",
      amount: "Сумма на бумагу",
      percent: "% к номиналу",
      window: "Период выплаты",
      form: "Стандарт",
      period: "Период",
      isin: "ISIN",
      nominal: "Номинал",
      openCompany: "Страница компании",
      openAnnouncement: "Текст объявления",
      openNews: "Открыть на сайте",
      openSource: "Источник на openinfo.uz",
      pdf: "PDF",
      excel: "Excel",
      sum: "сум",
    },
    about: {
      meeting: "Общее собрание акционеров, созванное эмитентом. Дата — из сообщения о созыве.",
      notice: "Сообщение эмитента о созыве общего собрания, датой публикации.",
      dividend: {
        decision: "Собрание приняло решение о выплате дивидендов.",
        payment_start: "Начинается выплата объявленных дивидендов.",
        payment_end: "Последний день выплаты объявленных дивидендов.",
      },
      bond: {
        decision: "Эмитент объявил выплату дохода по облигациям.",
        payment_start: "Начинается выплата дохода по облигациям.",
        payment_end: "Последний день выплаты дохода по облигациям.",
      },
      report: "Эмитент раскрыл финансовую отчётность на бирже.",
      fact: "Существенный факт из ленты раскрытия эмитента.",
      listing: "Бумага допущена к торгам на Республиканской фондовой бирже «Тошкент».",
    },
    note: "Даты выплат — окно, которое эмитент указал в решении. Дату закрытия реестра и экс-дивидендную дату openinfo.uz не публикует, поэтому их нет. Сроки отчётности не прогнозируются.",
    source: "Источник: openinfo.uz, РФБ «Тошкент»",
  },
  en: {
    views: { month: "Month", week: "Week", list: "List" },
    today: "Today",
    prev: "Previous",
    next: "Next",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    types: {
      meeting: "Meetings",
      dividend: "Dividends",
      report: "Reports",
      fact: "Material facts",
      notice: "Announcements",
      listing: "Listings",
    },
    typeOne: {
      meeting: "Shareholder meeting",
      dividend: "Dividend",
      report: "Financial report",
      fact: "Material fact",
      notice: "Meeting notice",
      listing: "Listing",
    },
    divKinds: { decision: "Dividend declared", payment_start: "Payment starts", payment_end: "Payment ends" },
    bondKinds: { decision: "Bond income declared", payment_start: "Bond income payment starts", payment_end: "Bond income payment ends" },
    divClasses: { ordinary: "Ordinary shares", preferred: "Preferred shares", bond: "Bonds" },
    allTypes: "All types",
    companyPh: "Company or ticker…",
    from: "From",
    to: "to",
    resetFilters: "Reset filters",
    upcoming: "Coming up",
    upcomingEmpty: "No announced events in the next 60 days.",
    inDays: (n) => (n === 0 ? "today" : n === 1 ? "tomorrow" : `in ${n} days`),
    daysAgo: (n) => (n === 1 ? "yesterday" : `${n} days ago`),
    loading: "Loading the calendar…",
    error: "Could not load the calendar.",
    partial: "Some sources are unavailable right now — showing the rest.",
    empty: "No events in this period.",
    emptyFiltered: "No events match the filters.",
    more: (n) => `${n} more`,
    dayEvents: (n) => `${n} event${n === 1 ? "" : "s"}`,
    wholePeriod: "Whole period",
    download: "Download CSV",
    close: "Close",
    upcomingTag: "Upcoming",
    pastTag: "Past",
    todayTag: "Today",
    noticeFor: (d) => `Meeting called for ${d}`,
    reportTitle: (form, period) => `${form} report${period ? ` for ${period}` : ""}`.trim(),
    listingTitle: (kind) => `Admitted to trading: ${kind}`,
    shareTypes: { ordinary: "ordinary shares", preferred: "preferred shares", bond: "bonds" },
    d: {
      company: "Company",
      ticker: "Ticker",
      date: "Date",
      time: "Time",
      type: "Event type",
      decision: "Decision date",
      published: "Published",
      meeting: "Meeting date",
      cls: "Security",
      amount: "Amount per security",
      percent: "% of par",
      window: "Payment window",
      form: "Standard",
      period: "Period",
      isin: "ISIN",
      nominal: "Par value",
      openCompany: "Company page",
      openAnnouncement: "Announcement text",
      openNews: "Open on site",
      openSource: "Source on openinfo.uz",
      pdf: "PDF",
      excel: "Excel",
      sum: "UZS",
    },
    about: {
      meeting: "A general meeting of shareholders called by the issuer. The date is from the notice.",
      notice: "The issuer's notice calling a general meeting, dated by publication.",
      dividend: {
        decision: "The meeting resolved to pay a dividend.",
        payment_start: "Payment of the declared dividend begins.",
        payment_end: "The last day of payment of the declared dividend.",
      },
      bond: {
        decision: "The issuer declared an income payment on its bonds.",
        payment_start: "Payment of bond income begins.",
        payment_end: "The last day of payment of bond income.",
      },
      report: "The issuer disclosed financial statements on the exchange.",
      fact: "A material fact from the issuer's disclosure feed.",
      listing: "The security was admitted to trading on the Tashkent Stock Exchange.",
    },
    note: "Payment dates are the window the issuer stated in its resolution. openinfo.uz publishes no record or ex-dividend date, so none are shown. Report deadlines are not forecast.",
    source: "Source: openinfo.uz, Tashkent Stock Exchange",
  },
  uz: {
    views: { month: "Oy", week: "Hafta", list: "Ro'yxat" },
    today: "Bugun",
    prev: "Orqaga",
    next: "Oldinga",
    weekdays: ["Du", "Se", "Ch", "Pa", "Ju", "Sh", "Ya"],
    types: {
      meeting: "Yig'ilishlar",
      dividend: "Dividendlar",
      report: "Hisobotlar",
      fact: "Muhim faktlar",
      notice: "E'lonlar",
      listing: "Listing",
    },
    typeOne: {
      meeting: "Aksiyadorlar yig'ilishi",
      dividend: "Dividend",
      report: "Moliyaviy hisobot",
      fact: "Muhim fakt",
      notice: "Yig'ilish haqida e'lon",
      listing: "Listing",
    },
    divKinds: { decision: "Dividend qarori", payment_start: "To'lov boshlanishi", payment_end: "To'lov tugashi" },
    bondKinds: { decision: "Obligatsiya daromadi qarori", payment_start: "Daromad to'lovi boshlanishi", payment_end: "Daromad to'lovi tugashi" },
    divClasses: { ordinary: "Oddiy aksiyalar", preferred: "Imtiyozli aksiyalar", bond: "Obligatsiyalar" },
    allTypes: "Barcha turlar",
    companyPh: "Kompaniya yoki tiker…",
    from: "Dan",
    to: "gacha",
    resetFilters: "Filtrlarni tozalash",
    upcoming: "Yaqin voqealar",
    upcomingEmpty: "Keyingi 60 kunda e'lon qilingan voqealar yo'q.",
    inDays: (n) => (n === 0 ? "bugun" : n === 1 ? "ertaga" : `${n} kundan keyin`),
    daysAgo: (n) => (n === 1 ? "kecha" : `${n} kun oldin`),
    loading: "Taqvim yuklanmoqda…",
    error: "Taqvimni yuklab bo'lmadi.",
    partial: "Ba'zi manbalar hozir mavjud emas — qolganlari ko'rsatilmoqda.",
    empty: "Bu davrda voqealar yo'q.",
    emptyFiltered: "Filtrlarga mos voqealar yo'q.",
    more: (n) => `yana ${n}`,
    dayEvents: (n) => `${n} ta voqea`,
    wholePeriod: "Butun davr",
    download: "CSV yuklab olish",
    close: "Yopish",
    upcomingTag: "Kutilmoqda",
    pastTag: "O'tgan",
    todayTag: "Bugun",
    noticeFor: (d) => `Yig'ilish ${d} ga chaqirilgan`,
    reportTitle: (form, period) => `${form} hisoboti${period ? ` (${period})` : ""}`.trim(),
    listingTitle: (kind) => `Savdoga kiritildi: ${kind}`,
    shareTypes: { ordinary: "oddiy aksiyalar", preferred: "imtiyozli aksiyalar", bond: "obligatsiyalar" },
    d: {
      company: "Kompaniya",
      ticker: "Tiker",
      date: "Sana",
      time: "Vaqt",
      type: "Voqea turi",
      decision: "Qaror sanasi",
      published: "E'lon qilingan",
      meeting: "Yig'ilish sanasi",
      cls: "Qimmatli qog'oz",
      amount: "Bir qog'ozga summa",
      percent: "Nominalga %",
      window: "To'lov davri",
      form: "Standart",
      period: "Davr",
      isin: "ISIN",
      nominal: "Nominal",
      openCompany: "Kompaniya sahifasi",
      openAnnouncement: "E'lon matni",
      openNews: "Saytda ochish",
      openSource: "openinfo.uz dagi manba",
      pdf: "PDF",
      excel: "Excel",
      sum: "so'm",
    },
    about: {
      meeting: "Emitent chaqirgan aksiyadorlar umumiy yig'ilishi. Sana — chaqiruv xabaridan.",
      notice: "Emitentning umumiy yig'ilish chaqirilishi haqidagi xabari, e'lon sanasi bo'yicha.",
      dividend: {
        decision: "Yig'ilish dividend to'lash to'g'risida qaror qabul qildi.",
        payment_start: "E'lon qilingan dividend to'lovi boshlanadi.",
        payment_end: "E'lon qilingan dividend to'lovining oxirgi kuni.",
      },
      bond: {
        decision: "Emitent obligatsiyalar bo'yicha daromad to'lashni e'lon qildi.",
        payment_start: "Obligatsiyalar bo'yicha daromad to'lovi boshlanadi.",
        payment_end: "Obligatsiyalar bo'yicha daromad to'lovining oxirgi kuni.",
      },
      report: "Emitent birjada moliyaviy hisobotni oshkor qildi.",
      fact: "Emitentning oshkor qilish lentasidagi muhim fakt.",
      listing: "Qimmatli qog'oz «Toshkent» RFBda savdoga kiritildi.",
    },
    note: "To'lov sanalari — emitent qarorida ko'rsatgan davr. Reyestr yopilish va ex-dividend sanalarini openinfo.uz e'lon qilmaydi, shuning uchun ular yo'q. Hisobot muddatlari bashorat qilinmaydi.",
    source: "Manba: openinfo.uz, «Toshkent» RFB",
  },
};

function plural(n, one, few, many) {
  const m10 = n % 10;
  const m100 = n % 100;
  if (m10 === 1 && m100 !== 11) return one;
  if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return few;
  return many;
}

export const NEWS_CALENDAR_POLL_MS = 5 * 60 * 1000;

export function calendarAnnouncementPath(item) {
  const id = String(item?.announcement_id || "").trim();
  if (!id) return "";
  return `/news/announcement/${encodeURIComponent(id)}`;
}
