import { normalizeLanguage } from "../../shared/i18n.jsx";

const COMPARE_TEXTS = {
  ru: {
    nav: "Сравнение",
    title: "Сравнение эмитентов",
    subtitle: "Сравните 2-5 компаний по МСФО, рыночной ликвидности, отчетам и нормализованным показателям 0-100.",
    company1: "Компания 1",
    company2: "Компания 2",
    company3: "Компания 3",
    company4: "Компания 4",
    company5: "Компания 5",
    placeholder: "Тикер или название компании",
    optional: "необязательно",
    includeAi: "Сформировать comparative AI summary",
    submit: "Сравнить",
    loading: "Сравнение выполняется...",
    ready: "Сравнение готово",
    authRequired: "Сначала выполните вход",
    minRequired: "Выберите минимум две разные компании",
    overview: "Итог сравнения",
    leaders: "Лидеры по ключевым блокам",
    charts: "Сравнительные графики",
    tables: "Сравнительные таблицы",
    aiSummary: "Comparative AI summary",
    methodology: "Методика",
    ranking: "Рейтинг",
    normalizedRanking: "Нормализованный рейтинг",
    normalizedNote: "Все разнородные метрики приведены к шкале 0-100: чем выше, тем сильнее позиция компании.",
    noData: "Нет данных",
    empty: "Добавьте 2-5 компаний и запустите сравнение.",
    quick: "Быстрый выбор",
    errors: "Предупреждения",
    raw: "значение",
    normalized: "норм.",
    rank: "место",
  },
  en: {
    nav: "Compare",
    title: "Issuer comparison",
    subtitle: "Compare 2-5 companies by IFRS metrics, market liquidity, reports, and normalized 0-100 indicators.",
    company1: "Company 1",
    company2: "Company 2",
    company3: "Company 3",
    company4: "Company 4",
    company5: "Company 5",
    placeholder: "Ticker or company name",
    optional: "optional",
    includeAi: "Generate comparative AI summary",
    submit: "Compare",
    loading: "Comparison is running...",
    ready: "Comparison is ready",
    authRequired: "Please sign in first",
    minRequired: "Select at least two different companies",
    overview: "Comparison result",
    leaders: "Leaders by key blocks",
    charts: "Comparative charts",
    tables: "Comparative tables",
    aiSummary: "Comparative AI summary",
    methodology: "Methodology",
    ranking: "Ranking",
    normalizedRanking: "Normalized ranking",
    normalizedNote: "Different metrics are normalized to a 0-100 scale: higher means a stronger relative position.",
    noData: "No data",
    empty: "Add 2-5 companies and run comparison.",
    quick: "Quick pick",
    errors: "Warnings",
    raw: "value",
    normalized: "norm.",
    rank: "rank",
  },
  uz: {
    nav: "Taqqoslash",
    title: "Emitentlarni taqqoslash",
    subtitle: "2-5 kompaniyani IFRS ko'rsatkichlari, bozor likvidligi, hisobotlar va 0-100 normalizatsiya bo'yicha solishtiring.",
    company1: "Kompaniya 1",
    company2: "Kompaniya 2",
    company3: "Kompaniya 3",
    company4: "Kompaniya 4",
    company5: "Kompaniya 5",
    placeholder: "Ticker yoki kompaniya nomi",
    optional: "ixtiyoriy",
    includeAi: "Comparative AI summary yaratish",
    submit: "Taqqoslash",
    loading: "Taqqoslash bajarilmoqda...",
    ready: "Taqqoslash tayyor",
    authRequired: "Avval tizimga kiring",
    minRequired: "Kamida ikki xil kompaniyani tanlang",
    overview: "Taqqoslash natijasi",
    leaders: "Asosiy bloklar bo'yicha liderlar",
    charts: "Taqqoslash grafiklari",
    tables: "Taqqoslash jadvallari",
    aiSummary: "Comparative AI summary",
    methodology: "Metodika",
    ranking: "Reyting",
    normalizedRanking: "Normalizatsiya reytingi",
    normalizedNote: "Turli metrikalar 0-100 shkalasiga keltiriladi: yuqori qiymat nisbatan kuchliroq pozitsiyani bildiradi.",
    noData: "Ma'lumot yo'q",
    empty: "2-5 kompaniya qo'shing va taqqoslashni boshlang.",
    quick: "Tez tanlash",
    errors: "Ogohlantirishlar",
    raw: "qiymat",
    normalized: "norm.",
    rank: "o'rin",
  },
};

function ct(language, key) {
  const lang = normalizeLanguage(language);
  return COMPARE_TEXTS[lang]?.[key] ?? COMPARE_TEXTS.ru[key] ?? key;
}

export { ct };
