COMPANY_CATALOG = {
    '"Hamkorbank" ATB': "HMKB",
    '"Hamkorbank" ATB (привилегированные)': "HMKBP",
    '"Ipak Yuli" ATIB': "IPKY",
    '"Ipoteka-bank" ATIB': "IPTB",
    '"Ipoteka-bank" ATIB (привилегированные)': "IPTBP",
    '"Agrobank" ATB': "AGBA",
    '"Agrobank" ATB (привилегированные)': "AGBAP",
    '"O\'zsanoatqurilishbank" ATB': "SQBN",
    '"O\'zsanoatqurilishbank" ATB (привилегированные)': "SQBNP",
    '"Trastbank" CHAKB': "TRSB",
    '"Trastbank" CHAKB (привилегированные)': "TRSBP",
    '"Turonbank" ATB': "TNBN",
    '"Turonbank" ATB (привилегированные)': "TNBNP",
    '"Aloqabank" ATB': "ALKB",
    '"Aloqabank" ATB (привилегированные)': "ALKBP",
    '"Garant Bank" AJ': "GRBK",
    '"Mikrokreditbank" ATB': "MCBA",
    '"Mikrokreditbank" ATB (привилегированные)': "MCBAP",
    '"Universal Bank" CHAKB': "UNVB",
    '"Oktobank" AJ': "OCBK",
    '"Biznesni rivojlantirish banki" ATB': "BRBN",
    '"Biznesni rivojlantirish banki" ATB (привилегированные)': "BRNBP",
    '"Kapitalbank" AJ': "KPBA",
    '"Tenge Bank" ATB': "TNGB",
    '"O\'zRTXB" AJ': "URTS",
    '"O\'zmetkombinat" AJ': "UZMK",
    '"O\'zmetkombinat" AJ (привилегированные)': "UZMKP",
    '"Kvarts" AJ': "KVTS",
    '"Qizilqumsement" AJ': "QZSM",
    '"Bekobodsement" AJ': "BECM",
    '"Bekobodsement" AJ (привилегированные)': "BECMP",
    '"Olmaliq KMK" AJ (привилегированные)': "AGMKP",
    '"UzAuto Motors" AJ': "UZMT",
    '"DORI-DARMON" AJ': "DORI",
    '"Buxoroneftgazparmalash" AJ': "BNGP",
    '"Buxoroneftgazparmalash" AJ (привилегированные)': "BNGPP",
    '"O\'zbekiston neftgaz" AJ (привилегированные)': "UZNGP",
    '"Mubarekneftgazmontaj" AJ': "MNGM",
    '"O\'zbekgeofizika" AJ (привилегированные)': "UZGFP",
    '"O\'ztransgaz" AJ (привилегированные)': "UTGAP",
    '"Neft va gaz quduqlarini sinash" AJ': "NGQS",
    '"O\'zbektelekom" AJ': "UZTL",
    '"Boshtransloyiha" AJ': "BTRL",
    '"O\'zbekko\'mir" AJ': "UZIR",
    '"O\'zbekinvest EISK" AJ (привилегированные)': "UZINP",
    '"ALSKOM sug\'urta" AJ': "ALSM",
    '"Kapital sug\'urta" AJ (привилегированные)': "KASUP",
    '"Chilonzor buyum savdo kompleksi" AJ': "CBSK",
    '"JSM" AJ': "JASM",
    '"ORGRES" AJ': "ORGS",
    '"TDM" AJ (привилегированные)': "TKDMP",
}

# Sector classification for each ticker.
# Keys match COMPANY_CATALOG values (tickers).
COMPANY_SECTORS: dict[str, str] = {
    # Finance & Insurance
    "HMKB": "finance", "HMKBP": "finance",
    "IPKY": "finance",
    "IPTB": "finance", "IPTBP": "finance",
    "AGBA": "finance", "AGBAP": "finance",
    "SQBN": "finance", "SQBNP": "finance",
    "TRSB": "finance", "TRSBP": "finance",
    "TNBN": "finance", "TNBNP": "finance",
    "ALKB": "finance", "ALKBP": "finance",
    "GRBK": "finance",
    "MCBA": "finance", "MCBAP": "finance",
    "UNVB": "finance",
    "OCBK": "finance",
    "BRBN": "finance", "BRNBP": "finance",
    "KPBA": "finance",
    "TNGB": "finance",
    "URTS": "finance",
    "UZINP": "finance",
    "ALSM": "finance",
    "KASUP": "finance",
    # Manufacturing
    "UZMK": "manufacturing", "UZMKP": "manufacturing",
    "KVTS": "manufacturing",
    "QZSM": "manufacturing",
    "BECM": "manufacturing", "BECMP": "manufacturing",
    "UZMT": "manufacturing",
    "DORI": "manufacturing",
    "ORGS": "manufacturing",
    # Mining & Extraction
    "AGMKP": "mining",
    "BNGP": "mining", "BNGPP": "mining",
    "UZNGP": "mining",
    "MNGM": "mining",
    "UZGFP": "mining",
    "NGQS": "mining",
    "UZIR": "mining",
    # Transport
    "UTGAP": "transport",
    # Telecom & IT
    "UZTL": "telecom",
    # Professional Services
    "BTRL": "professional",
    # Trade
    "CBSK": "trade",
    # Other
    "JASM": "other",
    "TKDMP": "other",
}
