"""pg_migrate.py — copy the SQLite databases into PostgreSQL, and prove it.

Phase one of the move described in ТЗ §10.1. It is deliberately additive and
reversible: tables are created alongside whatever PostgreSQL already holds (here,
the five web-auth tables), the SQLite files are never modified, and nothing that
serves a request changes until `DATABASE_BACKEND` is flipped. If the result is
wrong, dropping the copied tables restores the previous state exactly.

The part that matters is not the copy — it is the verification. A migration that
moves rows without comparing them afterwards is a migration you will be arguing
about in three weeks. Every table is checked on row count AND on a checksum of
its contents, and the run fails if a single one disagrees.

Two type decisions, both from §10.1:

  REAL becomes NUMERIC. SQLite has no decimal type, so a price of 0.01 and a
  capitalisation in the trillions share one float64. This is the correctness
  reason for the whole exercise.

  Everything else keeps its SQLite affinity. Guessing narrower types would be
  the same class of mistake as inventing a bond's par value.
"""
from __future__ import annotations

import hashlib
import logging
import os
import re
import sqlite3
from pathlib import Path
from typing import Any, Iterable, Sequence

logger = logging.getLogger(__name__)

DATA_DIR = Path(os.getenv("APP_DATA_DIR") or Path(__file__).with_name("data"))
SOURCES = ("reports_catalog.db", "securities.db", "analysis_cache.db")

# PostgreSQL owns these already; the copy must not touch them.
PROTECTED = {"web_users", "web_sessions", "web_oauth_accounts",
             "web_favorite_companies", "web_analysis_history", "schema_migrations"}

_TYPE_MAP = (
    (re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.I),
     "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    (re.compile(r"\bAUTOINCREMENT\b", re.I), ""),
    (re.compile(r"\bREAL\b", re.I), "NUMERIC"),
    # BEFORE the DATETIME→TEXT rule, and rendered as the same TEXT the rest of
    # this project writes its clocks in (dbx._PG_NOW). Both details were wrong:
    # `\bDATETIME\b` fired first and turned `DEFAULT (datetime('now'))` into
    # `DEFAULT (TEXT('now'))` — a cast of the literal string, so every row
    # relying on that default was stamped «now», the word. catalog_new_reports
    # was the one table that did rely on it, and 195 of its 199 rows on prod
    # carried «now»: a string that sorts above every real date and satisfies
    # every `>= datetime('now', ?)` window, so those events pinned themselves to
    # the head of the market-events timeline and no cleanup could ever reach
    # them. And `now()` would have been wrong in its own way — a timestamp cast
    # into a TEXT column writes a different format from every neighbouring row.
    (re.compile(r"\bdatetime\s*\(\s*'now'\s*\)", re.I),
     "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"),
    (re.compile(r"\bDATETIME\b", re.I), "TEXT"),
    (re.compile(r"\bBLOB\b", re.I), "BYTEA"),
)


def _sqlite(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    return conn


def source_tables(conn: sqlite3.Connection) -> list[str]:
    return [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name")]


def translate_ddl(ddl: str) -> str:
    """A SQLite CREATE TABLE, in PostgreSQL's dialect."""
    out = ddl
    for pattern, replacement in _TYPE_MAP:
        out = pattern.sub(replacement, out)
    # SQLite tolerates a bare `IF NOT EXISTS` on any object; PostgreSQL does too,
    # but the statement must name the table without a schema prefix.
    return out.replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", 1) \
        if "IF NOT EXISTS" not in out else out


def checksum(rows: Iterable[Sequence[Any]]) -> str:
    """Order-independent digest of a table's contents.

    Order-independent on purpose: PostgreSQL makes no promise about the order of
    an unqualified SELECT, and a checksum that depends on it would report a
    difference every run and teach everyone to ignore it.
    """
    digest = hashlib.sha256()
    for line in sorted("\x1f".join("" if v is None else str(v) for v in row)
                       for row in rows):
        digest.update(line.encode("utf-8"))
        digest.update(b"\x1e")
    return digest.hexdigest()[:32]


def create_table(sqlite_conn: sqlite3.Connection, pg: Any, table: str,
                 schema: str = "public") -> None:
    """The table's shape, translated. Idempotent."""
    ddl_row = sqlite_conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name = ?", (table,)).fetchone()
    if not ddl_row or not ddl_row[0]:
        return
    with pg.cursor() as cur:
        cur.execute(f'SET search_path TO "{schema}"')
        cur.execute(translate_ddl(ddl_row[0]))


def copy_table(sqlite_conn: sqlite3.Connection, pg: Any, table: str,
               batch: int = 1000, schema: str = "public") -> dict[str, Any]:
    """Fill one table. Existing rows are replaced, not appended."""
    with pg.cursor() as cur:
        cur.execute(f'SET search_path TO "{schema}"')
        cur.execute(f'TRUNCATE TABLE "{table}" CASCADE')

    columns = [r[1] for r in sqlite_conn.execute(f"PRAGMA table_info({table})")]
    quoted = ", ".join(f'"{c}"' for c in columns)
    placeholders = ", ".join(["%s"] * len(columns))
    rows = sqlite_conn.execute(f'SELECT {quoted} FROM "{table}"').fetchall()

    with pg.cursor() as cur:
        for start in range(0, len(rows), batch):
            cur.executemany(
                f'INSERT INTO "{table}" ({quoted}) VALUES ({placeholders})',
                [tuple(r) for r in rows[start:start + batch]])
    pg.commit()
    synced = sync_identity(pg, table, schema=schema)
    return {"table": table, "columns": len(columns), "rows": len(rows),
            "identity": synced}


def identity_columns(pg: Any, schema: str = "public") -> list[tuple[str, str]]:
    """Every (table, column) in the schema whose value PostgreSQL generates."""
    with pg.cursor() as cur:
        cur.execute(
            """
            SELECT c.relname, a.attname
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid
            WHERE c.relkind = 'r' AND n.nspname = %s
              AND a.attidentity <> '' AND NOT a.attisdropped
            ORDER BY 1, 2
            """,
            (schema,))
        return [(r[0], r[1]) for r in cur.fetchall()]


def sync_identity(pg: Any, table: str, schema: str = "public") -> list[dict[str, Any]]:
    """Move each generated key past the rows that were copied in with their own ids.

    `GENERATED BY DEFAULT AS IDENTITY` accepts an explicit id — which is what makes
    the copy faithful — but it does not advance the sequence behind it. Left alone,
    the first row the *application* inserts asks for id 1, and PostgreSQL rejects it
    against a table whose ids already run to 630. That is not a hypothetical: it is
    how the news feed stopped on 2026-08-01. The failure is silent from the outside
    (every read still works) and permanent until someone runs this, so the sequence
    is fixed here, in the same breath as the copy, rather than remembered later.

    Idempotent: it reads the table's own MAX and sets the sequence to it.
    """
    synced: list[dict[str, Any]] = []
    for tbl, col in identity_columns(pg, schema):
        if tbl != table:
            continue
        with pg.cursor() as cur:
            cur.execute(f'SET search_path TO "{schema}"')
            # is_called=false when the table is empty, so the first id is 1, not 2.
            cur.execute(
                f'SELECT setval(pg_get_serial_sequence(%s, %s), '
                f'  GREATEST(COALESCE(MAX("{col}"), 0), 1), MAX("{col}") IS NOT NULL) '
                f'FROM "{tbl}"',
                (f"{schema}.{tbl}", col))
            row = cur.fetchone()
        synced.append({"table": tbl, "column": col, "next_id": int(row[0]) + 1})
    pg.commit()
    return synced


def sync_all_identities(url: str | None = None, schema: str = "public") -> dict[str, Any]:
    """Repair every generated key in an existing database (see :func:`sync_identity`)."""
    import psycopg

    url = url or os.getenv("DATABASE_URL") or ""
    if not url:
        raise RuntimeError("DATABASE_URL is not set")
    synced: list[dict[str, Any]] = []
    with psycopg.connect(url, connect_timeout=30) as pg:
        for tbl, _col in identity_columns(pg, schema):
            synced.extend(sync_identity(pg, tbl, schema=schema))
    return {"ok": True, "schema": schema, "synced": synced}


def _same(a: Any, b: Any, rel_tol: float = 1e-12) -> bool:
    """Are these the same value?

    Numbers are compared with a relative tolerance, and that is not laxity — it
    is the whole reason for the migration. SQLite holds every number as float64,
    which cannot represent 6853225471.87 and stores 6853225471.870001 instead.
    PostgreSQL NUMERIC holds the decimal exactly. Demanding string equality
    would report the removal of that error as a data loss.

    The tolerance is 1e-12, chosen against both failure modes rather than by
    feel. The artefact above is a relative difference of 1.5e-16 — float64's
    own resolution — so it passes. A liability of 6 853 225 471.87 that differs
    by one sum is a relative difference of 1.5e-10, four orders larger, and
    fails. A looser 1e-9 would have swallowed it.
    """
    if a is None or b is None:
        return a is None and b is None
    a_num = isinstance(a, (int, float)) or hasattr(a, "as_tuple")
    b_num = isinstance(b, (int, float)) or hasattr(b, "as_tuple")
    if a_num and b_num:
        x, y = float(a), float(b)
        if x == y:
            return True
        scale = max(abs(x), abs(y))
        return scale > 0 and abs(x - y) / scale <= rel_tol
    return str(a) == str(b)


def verify_table(sqlite_conn: sqlite3.Connection, pg: Any, table: str,
                 schema: str = "public") -> dict[str, Any]:
    """Row count and a value-by-value comparison. Either failing fails the run.

    Rows are matched on their non-numeric columns, because those identify a row
    and cannot drift; the numeric ones are then compared with tolerance. The
    count of values that differed only by float artefact is reported, because it
    measures exactly what the move to NUMERIC bought.
    """
    columns = [r[1] for r in sqlite_conn.execute(f"PRAGMA table_info({table})")]
    quoted = ", ".join(f'"{c}"' for c in columns)
    src = [tuple(r) for r in sqlite_conn.execute(f'SELECT {quoted} FROM "{table}"')]
    with pg.cursor() as cur:
        cur.execute(f'SET search_path TO "{schema}"')
        cur.execute(f'SELECT {quoted} FROM "{table}"')
        dst = [tuple(r) for r in cur.fetchall()]

    def key(row):
        return tuple("" if v is None else str(v) for i, v in enumerate(row)
                     if not (isinstance(v, (int, float)) or hasattr(v, "as_tuple")))

    remaining: dict[Any, list[tuple]] = {}
    for row in dst:
        remaining.setdefault(key(row), []).append(row)

    mismatches: list[dict[str, Any]] = []
    healed = 0
    for row in src:
        candidates = remaining.get(key(row)) or []
        match = None
        for candidate in candidates:
            if all(_same(a, b) for a, b in zip(row, candidate)):
                match = candidate
                break
        if match is None:
            if len(mismatches) < 5:
                mismatches.append({"source_row": [str(v)[:40] for v in row]})
            continue
        healed += sum(1 for a, b in zip(row, match)
                      if a is not None and str(a) != str(b))
        candidates.remove(match)

    ok = len(src) == len(dst) and not mismatches
    return {"table": table, "source_rows": len(src), "target_rows": len(dst),
            # Values whose text changed but whose VALUE did not: float error the
            # decimal type removed.
            "float_artifacts_removed": healed,
            "mismatches": mismatches, "ok": ok}


def _in_dependency_order(items, attempt, on_give_up):
    """Run `attempt` over `items`, retrying failures until a pass adds nothing.

    Foreign keys impose an order that alphabetical listing does not: bond_coupons
    precedes bond_reference, report_figures precedes source_reports. Parsing
    REFERENCES out of the DDL would mean writing a SQL parser to avoid writing a
    SQL parser; retrying resolves any acyclic set and reports a genuine cycle.
    """
    outstanding = list(items)
    while outstanding:
        failed, errors = [], {}
        for item in outstanding:
            try:
                attempt(item)
            except Exception as exc:  # noqa: BLE001 — probably an unmet dependency
                failed.append(item)
                errors[item[1]] = str(exc).strip().splitlines()[0]
        if len(failed) == len(outstanding):
            for item in failed:
                on_give_up(item, errors.get(item[1], "unresolved dependency"))
            return [i for i in items if i not in failed]
        outstanding = failed
    return list(items)


def migrate(url: str | None = None, *, only: Sequence[str] | None = None,
            dry_run: bool = False, schema: str = "public") -> dict[str, Any]:
    """Copy every SQLite table into PostgreSQL and verify the result.

    ``schema`` exists so the tool can be REHEARSED against the real server
    without touching what it serves. A rehearsal into a throwaway schema proves
    the mechanics — DDL translation, batching, checksums — on the actual
    PostgreSQL version, while `public` stays exactly as it was.

    It also guards against the mistake this parameter was added after nearly
    making: the SQLite files on a developer's machine are NOT the production
    ones. The real copy has to run where the volume is mounted, which is why
    there is an endpoint for it.
    """
    import psycopg

    url = url or os.getenv("DATABASE_URL") or os.getenv("DATABASE_PUBLIC_URL") or ""
    if not url:
        raise RuntimeError("no PostgreSQL URL: set DATABASE_URL")

    plan: list[tuple[Path, str]] = []
    for name in SOURCES:
        path = DATA_DIR / name
        if not path.exists():
            logger.warning("migrate: %s not found, skipped", path)
            continue
        conn = _sqlite(path)
        try:
            for table in source_tables(conn):
                if table in PROTECTED:
                    logger.info("migrate: %s is owned by PostgreSQL, skipped", table)
                    continue
                if only and table not in only:
                    continue
                plan.append((path, table))
        finally:
            conn.close()

    if dry_run:
        return {"ok": True, "dry_run": True,
                "tables": [t for _, t in plan], "count": len(plan)}

    copied: list[dict[str, Any]] = []
    verified: list[dict[str, Any]] = []
    with psycopg.connect(url, connect_timeout=30) as pg:
        if schema != "public":
            with pg.cursor() as cur:
                cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
            pg.commit()
        def _create(item):
            path, table = item
            conn = _sqlite(path)
            try:
                create_table(conn, pg, table, schema=schema)
                pg.commit()
            except Exception:
                pg.rollback()
                raise
            finally:
                conn.close()

        def _fill(item):
            path, table = item
            conn = _sqlite(path)
            try:
                copied.append(copy_table(conn, pg, table, schema=schema))
                verified.append(verify_table(conn, pg, table, schema=schema))
            except Exception:
                pg.rollback()
                raise
            finally:
                conn.close()

        def _give_up(item, error):
            verified.append({"table": item[1], "ok": False, "error": error})

        plan = _in_dependency_order(plan, _create, _give_up)
        # Filling is ordered the same way, and for the same reason: a child row
        # cannot name a parent row that has not been inserted yet.
        _in_dependency_order(plan, _fill, _give_up)

    failures = [v for v in verified if not v.get("ok")]
    return {
        "ok": not failures,
        "schema": schema,
        "tables": len(plan),
        "rows": sum(c.get("rows", 0) for c in copied),
        "copied": copied,
        "verified": verified,
        "failures": failures,
    }


if __name__ == "__main__":  # pragma: no cover
    import json
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    schema = next((a.split("=", 1)[1] for a in sys.argv if a.startswith("--schema=")),
                  "public")
    if "--sync-sequences" in sys.argv:
        # Repair a database that was migrated before copy_table did this itself.
        report = sync_all_identities(schema=schema)
    else:
        report = migrate(dry_run="--dry-run" in sys.argv, schema=schema)
    print(json.dumps(report, ensure_ascii=False, indent=1, default=str))
    sys.exit(0 if report["ok"] else 1)
