"""The database adapter (dbx.py).

Roughly a hundred SQLite-specific SQL sites exist across the project. Editing
each by hand would be a hundred chances to break a query in a way no test
notices — a WHERE clause that quietly matches nothing looks exactly like a day
with no data. Translating in one place is only safer if that place is tested to
the edges, which is what this file is.

The two properties that matter: a string literal is never rewritten, and
anything ambiguous is refused rather than guessed at.
"""
from __future__ import annotations

import os
import sqlite3
import threading

import pytest

import dbx


class TestLiteralSafety:
    """A `?` or a function name inside quotes is DATA, not syntax."""

    def test_a_placeholder_inside_a_literal_is_untouched(self):
        sql = "SELECT * FROM t WHERE note = 'why? because' AND id = ?"
        got = dbx.translate(sql, dbx.POSTGRES)
        assert "'why? because'" in got
        assert got.endswith("id = %s")

    def test_a_function_name_inside_a_literal_is_untouched(self):
        sql = "INSERT INTO t (msg, at) VALUES ('call datetime(''now'') later', datetime('now'))"
        got = dbx.translate(sql, dbx.POSTGRES)
        assert "'call datetime(''now'') later'" in got
        assert got.count("datetime(") == 1  # the one inside the literal, and no other

    def test_escaped_quotes_do_not_end_the_literal(self):
        sql = "SELECT 'it''s ? fine' AS a, ? AS b"
        got = dbx.translate(sql, dbx.POSTGRES)
        assert "'it''s ? fine'" in got
        assert got.count("%s") == 1

    def test_double_quoted_identifiers_are_left_alone(self):
        sql = 'SELECT "weird?column" FROM t WHERE x = ?'
        got = dbx.translate(sql, dbx.POSTGRES)
        assert '"weird?column"' in got and got.count("%s") == 1

    def test_an_unterminated_literal_does_not_lose_text(self):
        sql = "SELECT 'unclosed"
        assert dbx.translate(sql, dbx.POSTGRES) == sql


class TestDialect:
    def test_sqlite_is_a_no_op(self):
        sql = "SELECT IFNULL(a, ?) FROM t WHERE at > datetime('now')"
        assert dbx.translate(sql, dbx.SQLITE) == sql

    def test_the_functions_the_codebase_actually_uses(self):
        got = dbx.translate(
            "INSERT INTO t (a, b) VALUES (?, IFNULL(?, 0)) "
            "ON CONFLICT(a) DO UPDATE SET at = datetime('now')", dbx.POSTGRES)
        assert "%s" in got and "COALESCE(" in got and "now()" in got
        assert "IFNULL" not in got and "datetime(" not in got

    def test_autoincrement_becomes_an_identity_column(self):
        got = dbx.translate("id INTEGER PRIMARY KEY AUTOINCREMENT", dbx.POSTGRES)
        assert "GENERATED BY DEFAULT AS IDENTITY" in got and "AUTOINCREMENT" not in got

    def test_money_columns_stop_being_float(self):
        """§10.1: NUMERIC for every price and sum, float forbidden."""
        got = dbx.translate("CREATE TABLE t (price REAL, qty REAL)", dbx.POSTGRES)
        assert got.count("NUMERIC") == 2 and "REAL" not in got

    def test_on_conflict_is_left_alone(self):
        """Valid in both dialects — translating it would be the bug."""
        sql = "INSERT INTO t VALUES (?) ON CONFLICT(a) DO UPDATE SET b = excluded.b"
        got = dbx.translate(sql, dbx.POSTGRES)
        assert "ON CONFLICT(a) DO UPDATE SET b = excluded.b" in got


class TestTheClockIsText:
    """Every DATETIME column crossed over as TEXT, so the clock has to be text too.

    `published_at >= now()` does not compare in PostgreSQL — it raises, because the
    implicit casts to text went away in 8.3. This is what took the whole news module
    down after the cutover, and these are the shapes that took it down.
    """

    def test_now_renders_in_sqlites_own_format(self):
        got = dbx.translate("SELECT datetime('now')", dbx.POSTGRES)
        assert "to_char(" in got and "'YYYY-MM-DD HH24:MI:SS'" in got
        assert "AT TIME ZONE 'UTC'" in got  # SQLite's datetime('now') is UTC

    def test_a_window_arrives_as_a_parameter_not_a_literal(self):
        """`datetime('now', ?)` with `-30 days` bound — the shape the feed uses."""
        got = dbx.translate(
            "SELECT * FROM news WHERE published_at >= datetime('now', ?) LIMIT ?",
            dbx.POSTGRES)
        assert "::interval" in got
        assert "datetime(" not in got
        # One placeholder in, one placeholder out: the rewrite must not shift binding.
        assert got.count("%s") == 2

    def test_the_date_form_is_text_too(self):
        got = dbx.translate("SELECT date('now')", dbx.POSTGRES)
        assert "'YYYY-MM-DD'" in got and "current_date" not in got

    def test_group_concat_becomes_string_agg_with_sqlites_separator(self):
        got = dbx.translate(
            "SELECT (SELECT GROUP_CONCAT(e.ticker) FROM news_entities e) AS t", dbx.POSTGRES)
        assert "string_agg(e.ticker, ',')" in got

    def test_a_group_concat_we_cannot_prove_is_left_alone(self):
        """Its own separator, DISTINCT, an expression — rewritten by hand or not at all."""
        for sql in ("SELECT GROUP_CONCAT(a, '; ') FROM t",
                    "SELECT GROUP_CONCAT(DISTINCT a) FROM t",
                    "SELECT GROUP_CONCAT(upper(a)) FROM t"):
            assert "string_agg" not in dbx.translate(sql, dbx.POSTGRES)


class TestRefusals:
    """Ambiguity is refused, not guessed at."""

    def test_insert_or_replace_is_refused(self):
        with pytest.raises(dbx.UnsupportedStatement, match="ON CONFLICT"):
            dbx.check_supported("INSERT OR REPLACE INTO t VALUES (1)")

    def test_insert_or_ignore_is_refused(self):
        with pytest.raises(dbx.UnsupportedStatement, match="ON CONFLICT DO NOTHING"):
            dbx.check_supported("INSERT OR IGNORE INTO t VALUES (1)")

    def test_pragma_is_refused(self):
        with pytest.raises(dbx.UnsupportedStatement, match="PRAGMA"):
            dbx.check_supported("PRAGMA table_info(t)")

    def test_ordinary_sql_passes(self):
        dbx.check_supported("SELECT 1")


class TestRows:
    def test_a_row_reads_by_name_and_by_index(self):
        row = dbx.Row(["ticker", "price"], ["UZHM", 6100])
        assert row["ticker"] == "UZHM" and row[0] == "UZHM"
        assert row["price"] == 6100 and row[1] == 6100
        assert row.keys() == ["ticker", "price"]

    def test_it_is_still_a_dict(self):
        row = dbx.Row(["a"], [1])
        assert dict(row) == {"a": 1}


class TestAgainstSqlite:
    @pytest.fixture()
    def conn(self, tmp_path, monkeypatch):
        monkeypatch.setenv("DATABASE_BACKEND", "sqlite")
        dbx.reset_pools()
        conn = dbx.connect(str(tmp_path / "t.db"))
        conn.execute("CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, "
                     "ticker TEXT, price REAL, at TEXT)")
        conn.commit()
        yield conn
        conn.close()
        dbx.reset_pools()

    def test_round_trip(self, conn):
        conn.execute("INSERT INTO t (ticker, price, at) VALUES (?,?,datetime('now'))",
                     ("UZHM", 6100.0))
        conn.commit()
        row = conn.execute("SELECT ticker, price FROM t WHERE ticker = ?", ("UZHM",)).fetchone()
        assert row["ticker"] == "UZHM" and row["price"] == 6100.0

    def test_executescript_splits_on_real_semicolons(self, conn):
        conn.executescript("""
            CREATE TABLE a (x TEXT);
            INSERT INTO a VALUES ('one; two');
        """)
        conn.commit()
        assert conn.execute("SELECT x FROM a").fetchone()["x"] == "one; two"

    def test_introspection_without_pragma(self, conn):
        assert "t" in dbx.tables(conn)
        assert set(dbx.columns(conn, "t")) == {"id", "ticker", "price", "at"}

    def test_the_context_manager_commits_and_rolls_back(self, tmp_path, monkeypatch):
        monkeypatch.setenv("DATABASE_BACKEND", "sqlite")
        dbx.reset_pools()
        path = str(tmp_path / "c.db")
        with dbx.session(path) as c:
            c.execute("CREATE TABLE t (x INTEGER)")
            c.commit()
        with pytest.raises(RuntimeError):
            with dbx.connect(path) as c:
                c.execute("INSERT INTO t VALUES (1)")
                raise RuntimeError("boom")
        with dbx.session(path) as c:
            assert c.execute("SELECT COUNT(*) FROM t").fetchone()[0] == 0
        dbx.reset_pools()


class TestPool:
    def test_a_closed_connection_returns_to_the_pool(self, tmp_path, monkeypatch):
        """Call sites open and close per operation; a real close per call would
        spend a network round trip on nothing."""
        monkeypatch.setenv("DATABASE_BACKEND", "sqlite")
        dbx.reset_pools()
        path = str(tmp_path / "p.db")
        first = dbx.connect(path)
        first.execute("CREATE TABLE t (x INTEGER)")
        first.commit()
        first.close()
        second = dbx.connect(path)
        assert second is first          # reused, not reopened
        second.close()
        dbx.reset_pools()

    def test_it_survives_concurrent_use(self, tmp_path, monkeypatch):
        monkeypatch.setenv("DATABASE_BACKEND", "sqlite")
        dbx.reset_pools()
        path = str(tmp_path / "c.db")
        setup = dbx.connect(path)
        setup.execute("CREATE TABLE t (x INTEGER)")
        setup.commit()
        setup.close()

        errors: list[Exception] = []

        def worker(n: int) -> None:
            try:
                conn = dbx.connect(path)
                conn.execute("INSERT INTO t VALUES (?)", (n,))
                conn.commit()
                conn.close()
            except Exception as exc:  # noqa: BLE001
                errors.append(exc)

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(12)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        assert errors == []
        conn = dbx.connect(path)
        assert conn.execute("SELECT COUNT(*) FROM t").fetchone()[0] == 12
        conn.close()
        dbx.reset_pools()


class TestBackendSwitch:
    def test_the_switch_is_explicit(self, monkeypatch):
        """Deriving it from DATABASE_URL would have flipped this project the day
        PostgreSQL was attached for web auth alone."""
        monkeypatch.setenv("DATABASE_URL", "postgresql://example/db")
        monkeypatch.delenv("DATABASE_BACKEND", raising=False)
        assert dbx.backend() == dbx.SQLITE
        monkeypatch.setenv("DATABASE_BACKEND", "postgres")
        assert dbx.backend() == dbx.POSTGRES

    def test_postgres_without_a_url_fails_loudly(self, monkeypatch):
        monkeypatch.setenv("DATABASE_BACKEND", "postgres")
        monkeypatch.delenv("DATABASE_URL", raising=False)
        monkeypatch.delenv("DATABASE_PUBLIC_URL", raising=False)
        dbx.reset_pools()
        with pytest.raises(RuntimeError, match="DATABASE_URL"):
            dbx.connect("whatever.db")
        dbx.reset_pools()
        os.environ["DATABASE_BACKEND"] = "sqlite"


class TestCommentsAndNamedParameters:
    """Two bugs the port surfaced, both silent in the wrong way."""

    def test_a_comment_is_not_code(self):
        """A statement was refused for EXPLAINING itself: a comment reading
        "ON CONFLICT rather than INSERT OR REPLACE" tripped the rule it
        documented."""
        sql = ("-- ON CONFLICT rather than INSERT OR REPLACE\n"
               "INSERT INTO t VALUES (?) ON CONFLICT(a) DO NOTHING")
        dbx.check_supported(sql)                       # must not raise
        got = dbx.translate(sql, dbx.POSTGRES)
        assert got.count("%s") == 1                    # only the real placeholder

    def test_a_question_mark_in_a_comment_is_not_a_placeholder(self):
        """psycopg binds by counting %s — one introduced inside a comment
        shifts every parameter after it."""
        sql = "SELECT * FROM t -- why? because\nWHERE id = ?"
        assert dbx.translate(sql, dbx.POSTGRES).count("%s") == 1

    def test_block_comments_too(self):
        sql = "/* is this ? a placeholder */ SELECT ?"
        assert dbx.translate(sql, dbx.POSTGRES).count("%s") == 1

    def test_refusal_still_fires_on_real_code(self):
        with pytest.raises(dbx.UnsupportedStatement):
            dbx.check_supported("INSERT OR REPLACE INTO t VALUES (1)")

    def test_named_parameters_reach_the_driver_as_a_mapping(self, tmp_path, monkeypatch):
        """Wrapping a dict in tuple() yields the KEYS and binds nonsense."""
        monkeypatch.setenv("DATABASE_BACKEND", "sqlite")
        dbx.reset_pools()
        conn = dbx.connect(str(tmp_path / "n.db"))
        conn.execute("CREATE TABLE t (form TEXT, year INTEGER)")
        conn.execute("INSERT INTO t VALUES (:form, :year)", {"form": "NSBU", "year": 2025})
        conn.commit()
        row = conn.execute("SELECT form, year FROM t WHERE form = :form",
                           {"form": "NSBU"}).fetchone()
        assert row["form"] == "NSBU" and row["year"] == 2025
        conn.close()
        dbx.reset_pools()

    def test_named_parameters_are_rewritten_for_postgres(self):
        got = dbx._NAMED.sub(r"%(\1)s", "SELECT * FROM t WHERE form = :form AND y = :year")
        assert "%(form)s" in got and "%(year)s" in got

    def test_a_cast_is_not_a_parameter(self):
        assert dbx._NAMED.sub(r"%(\1)s", "SELECT x::text FROM t") == "SELECT x::text FROM t"


class TestIntrospectionAcceptsRawConnections:
    def test_a_raw_sqlite_connection_still_answers(self, tmp_path):
        """Migrations are handed either kind; guessing wrong returned "no
        columns", which reads as "the column is missing" and produces a
        duplicate-column error two lines later."""
        raw = sqlite3.connect(str(tmp_path / "raw.db"))
        raw.execute("CREATE TABLE t (a TEXT, b INTEGER)")
        assert set(dbx.columns(raw, "t")) == {"a", "b"}
        assert "t" in dbx.tables(raw)
