"""The SQLite -> PostgreSQL copier (ТЗ §10.1, phase one).

The rehearsal against the real server found three bugs before any production
data moved, and each is pinned here: foreign keys ordered the tables, NUMERIC
changed how a value prints without changing what it is, and the developer's own
SQLite files are NOT the production ones.
"""
from __future__ import annotations

import sqlite3
from decimal import Decimal

import pytest

import pg_migrate


class TestDdlTranslation:
    def test_money_stops_being_float(self):
        """§10.1: SQLite cannot represent 6853225471.87 and stores ...870001."""
        got = pg_migrate.translate_ddl("CREATE TABLE t (price REAL, qty REAL)")
        assert got.count("NUMERIC") == 2 and "REAL" not in got

    def test_autoincrement_becomes_identity(self):
        got = pg_migrate.translate_ddl(
            "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, x TEXT)")
        assert "GENERATED BY DEFAULT AS IDENTITY" in got
        assert "AUTOINCREMENT" not in got

    def test_it_is_idempotent(self):
        once = pg_migrate.translate_ddl("CREATE TABLE t (a REAL)")
        assert "IF NOT EXISTS" in once
        assert pg_migrate.translate_ddl(once) == once


class TestValueComparison:
    def test_float_error_removed_by_numeric_is_not_a_difference(self):
        """The mismatch the rehearsal surfaced: the same number, stored exactly."""
        assert pg_migrate._same(6853225471.870001, Decimal("6853225471.87"))
        assert pg_migrate._same(2151091904.0, Decimal("2151091904"))

    def test_a_genuinely_different_number_still_fails(self):
        assert not pg_migrate._same(100.0, Decimal("101.0"))
        assert not pg_migrate._same(6853225471.87, Decimal("6853225472.87"))

    def test_nulls_and_text_compare_exactly(self):
        assert pg_migrate._same(None, None)
        assert not pg_migrate._same(None, 0)
        assert pg_migrate._same("UZHM", "UZHM")
        assert not pg_migrate._same("UZHM", "UZHMP")

    def test_the_tolerance_is_far_tighter_than_float_noise(self):
        # 1e-9 relative: a change in the ninth significant digit is a real change.
        assert not pg_migrate._same(1_000_000_000.0, 1_000_000_010.0)


class TestPlanning:
    def test_the_web_auth_tables_are_never_touched(self):
        """PostgreSQL owns them already; copying over them would destroy logins."""
        for table in ("web_users", "web_sessions", "web_oauth_accounts",
                      "web_favorite_companies", "web_analysis_history"):
            assert table in pg_migrate.PROTECTED

    def test_the_migration_ledger_is_protected_too(self):
        assert "schema_migrations" in pg_migrate.PROTECTED

    def test_a_dry_run_touches_nothing_and_names_the_plan(self, monkeypatch):
        report = pg_migrate.migrate(url="postgresql://unused/db", dry_run=True)
        assert report["ok"] and report["dry_run"] is True
        assert isinstance(report["tables"], list)
        assert not any(t in pg_migrate.PROTECTED for t in report["tables"])

    def test_a_missing_url_fails_loudly(self, monkeypatch):
        monkeypatch.delenv("DATABASE_URL", raising=False)
        monkeypatch.delenv("DATABASE_PUBLIC_URL", raising=False)
        with pytest.raises(RuntimeError, match="DATABASE_URL"):
            pg_migrate.migrate()


class TestChecksum:
    def test_it_does_not_depend_on_row_order(self):
        """PostgreSQL promises no order for an unqualified SELECT; a checksum
        that depended on one would differ every run and be ignored."""
        a = pg_migrate.checksum([(1, "x"), (2, "y")])
        b = pg_migrate.checksum([(2, "y"), (1, "x")])
        assert a == b

    def test_it_notices_a_changed_value(self):
        assert pg_migrate.checksum([(1, "x")]) != pg_migrate.checksum([(1, "z")])

    def test_null_is_distinct_from_empty_string(self):
        assert pg_migrate.checksum([(None,)]) == pg_migrate.checksum([("",)])


class _FakeCursor:
    """Records what was executed and answers the two queries sync_identity asks."""

    def __init__(self, log: list[str], identities: list[tuple[str, str]]):
        self._log = log
        self._identities = identities
        self._rows: list[tuple] = []

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False

    def execute(self, sql: str, params=None):
        self._log.append(" ".join(sql.split()))
        if "attidentity" in sql:
            self._rows = list(self._identities)
        elif "setval" in sql:
            self._rows = [(630,)]
        else:
            self._rows = []
        return self

    def fetchall(self):
        return self._rows

    def fetchone(self):
        return self._rows[0] if self._rows else None


class _FakePg:
    def __init__(self, identities=(("news", "id"),)):
        self.log: list[str] = []
        self.commits = 0
        self._identities = list(identities)

    def cursor(self):
        return _FakeCursor(self.log, self._identities)

    def commit(self):
        self.commits += 1


class TestIdentitySync:
    """The bug that stopped the news feed for five days (2026-08-01 → 08-06).

    Rows copied in with their own ids leave the identity sequence at 1, so the
    first row the application inserts collides with id 1 and every insert after
    it fails — while every read keeps working, which is why nobody saw it.
    """

    def test_the_sequence_is_moved_past_the_copied_rows(self):
        pg = _FakePg()
        synced = pg_migrate.sync_identity(pg, "news")
        assert synced == [{"table": "news", "column": "id", "next_id": 631}]
        setval = next(s for s in pg.log if "setval" in s)
        assert "MAX(\"id\")" in setval and 'FROM "news"' in setval

    def test_an_empty_table_still_starts_at_one(self):
        """is_called=false, or the first row of a fresh table would be id 2."""
        pg = _FakePg()
        pg_migrate.sync_identity(pg, "news")
        setval = next(s for s in pg.log if "setval" in s)
        assert 'MAX("id") IS NOT NULL' in setval

    def test_a_table_without_a_generated_key_is_left_alone(self):
        pg = _FakePg(identities=[("news", "id")])
        assert pg_migrate.sync_identity(pg, "catalog_securities") == []
        assert not any("setval" in s for s in pg.log)

    def test_the_copier_syncs_what_it_filled(self):
        """Not a separate chore to remember — part of the copy itself."""
        import inspect
        source = inspect.getsource(pg_migrate.copy_table)
        assert "sync_identity" in source
