"""The SQLite -> PostgreSQL copier (ТЗ §10.1, phase one).

The rehearsal against the real server found three bugs before any production
data moved, and each is pinned here: foreign keys ordered the tables, NUMERIC
changed how a value prints without changing what it is, and the developer's own
SQLite files are NOT the production ones.
"""
from __future__ import annotations

import sqlite3
from decimal import Decimal

import pytest

import pg_migrate


class TestDdlTranslation:
    def test_money_stops_being_float(self):
        """§10.1: SQLite cannot represent 6853225471.87 and stores ...870001."""
        got = pg_migrate.translate_ddl("CREATE TABLE t (price REAL, qty REAL)")
        assert got.count("NUMERIC") == 2 and "REAL" not in got

    def test_autoincrement_becomes_identity(self):
        got = pg_migrate.translate_ddl(
            "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, x TEXT)")
        assert "GENERATED BY DEFAULT AS IDENTITY" in got
        assert "AUTOINCREMENT" not in got

    def test_it_is_idempotent(self):
        once = pg_migrate.translate_ddl("CREATE TABLE t (a REAL)")
        assert "IF NOT EXISTS" in once
        assert pg_migrate.translate_ddl(once) == once


class TestValueComparison:
    def test_float_error_removed_by_numeric_is_not_a_difference(self):
        """The mismatch the rehearsal surfaced: the same number, stored exactly."""
        assert pg_migrate._same(6853225471.870001, Decimal("6853225471.87"))
        assert pg_migrate._same(2151091904.0, Decimal("2151091904"))

    def test_a_genuinely_different_number_still_fails(self):
        assert not pg_migrate._same(100.0, Decimal("101.0"))
        assert not pg_migrate._same(6853225471.87, Decimal("6853225472.87"))

    def test_nulls_and_text_compare_exactly(self):
        assert pg_migrate._same(None, None)
        assert not pg_migrate._same(None, 0)
        assert pg_migrate._same("UZHM", "UZHM")
        assert not pg_migrate._same("UZHM", "UZHMP")

    def test_the_tolerance_is_far_tighter_than_float_noise(self):
        # 1e-9 relative: a change in the ninth significant digit is a real change.
        assert not pg_migrate._same(1_000_000_000.0, 1_000_000_010.0)


class TestPlanning:
    def test_the_web_auth_tables_are_never_touched(self):
        """PostgreSQL owns them already; copying over them would destroy logins."""
        for table in ("web_users", "web_sessions", "web_oauth_accounts",
                      "web_favorite_companies", "web_analysis_history"):
            assert table in pg_migrate.PROTECTED

    def test_the_migration_ledger_is_protected_too(self):
        assert "schema_migrations" in pg_migrate.PROTECTED

    def test_a_dry_run_touches_nothing_and_names_the_plan(self, monkeypatch):
        report = pg_migrate.migrate(url="postgresql://unused/db", dry_run=True)
        assert report["ok"] and report["dry_run"] is True
        assert isinstance(report["tables"], list)
        assert not any(t in pg_migrate.PROTECTED for t in report["tables"])

    def test_a_missing_url_fails_loudly(self, monkeypatch):
        monkeypatch.delenv("DATABASE_URL", raising=False)
        monkeypatch.delenv("DATABASE_PUBLIC_URL", raising=False)
        with pytest.raises(RuntimeError, match="DATABASE_URL"):
            pg_migrate.migrate()


class TestChecksum:
    def test_it_does_not_depend_on_row_order(self):
        """PostgreSQL promises no order for an unqualified SELECT; a checksum
        that depended on one would differ every run and be ignored."""
        a = pg_migrate.checksum([(1, "x"), (2, "y")])
        b = pg_migrate.checksum([(2, "y"), (1, "x")])
        assert a == b

    def test_it_notices_a_changed_value(self):
        assert pg_migrate.checksum([(1, "x")]) != pg_migrate.checksum([(1, "z")])

    def test_null_is_distinct_from_empty_string(self):
        assert pg_migrate.checksum([(None,)]) == pg_migrate.checksum([("",)])
