import { normalizeLanguage } from "../../shared/i18n.jsx";

const AUTH_PAGE_TEXTS = {
  ru: {
    title: "Войти в UZ Stock Analyzer",
    subtitle: "Ваши исследования и списки наблюдения синхронизируются после входа.",
    registerTitle: "Создать аккаунт",
    registerSubtitle: "Сохраняйте исследования, компании и заметки в одном рабочем пространстве.",
    remember: "Запомнить меня",
    showPassword: "Показать пароль",
    hidePassword: "Скрыть пароль",
    google: "Продолжить с Google",
    divider: "или",
    market: "Рынок UZSE",
    marketFallback: "Актуальные данные рынка Узбекистана",
    signedInTitle: "Аккаунт подключён",
    signedInSubtitle: "Вы уже вошли и можете продолжить работу в личном пространстве.",
    openProfile: "Открыть профиль",
    privacy: "Данные авторизации защищены и используются только для доступа к вашему аккаунту.",
    verifyTitle: "Подтвердите email",
    verifySubtitle: "Мы отправили 6-значный код на {email}. Введите его, чтобы завершить вход.",
    codeLabel: "Код из письма",
    verifySubmit: "Подтвердить",
    resend: "Отправить код ещё раз",
    resendIn: "Отправить снова через {seconds} с",
    resent: "Новый код отправлен. Проверьте также папку «Спам».",
    back: "Назад ко входу",
    verifiedSignIn: "Email подтверждён. Войдите, указав код из приложения-аутентификатора.",
    forgotLink: "Забыли пароль?",
    forgotTitle: "Восстановление пароля",
    forgotSubtitle: "Укажите email аккаунта — мы отправим код для сброса пароля.",
    forgotSubmit: "Отправить код",
    resetSubtitle: "Если аккаунт с адресом {email} существует, мы отправили на него код.",
    newPassword: "Новый пароль",
    resetSubmit: "Сменить пароль",
    resetDone: "Пароль изменён. Войдите с новым паролем.",
  },
  en: {
    title: "Sign in to UZ Stock Analyzer",
    subtitle: "Your research and watchlists sync after you sign in.",
    registerTitle: "Create an account",
    registerSubtitle: "Keep research, companies, and notes in one workspace.",
    remember: "Remember me",
    showPassword: "Show password",
    hidePassword: "Hide password",
    google: "Continue with Google",
    divider: "or",
    market: "UZSE market",
    marketFallback: "Current Uzbekistan market data",
    signedInTitle: "Account connected",
    signedInSubtitle: "You are already signed in and can continue to your workspace.",
    openProfile: "Open profile",
    privacy: "Authentication data is protected and used only to access your account.",
    verifyTitle: "Confirm your email",
    verifySubtitle: "We sent a 6-digit code to {email}. Enter it to finish signing in.",
    codeLabel: "Code from the email",
    verifySubmit: "Confirm",
    resend: "Send the code again",
    resendIn: "Send again in {seconds}s",
    resent: "A new code is on its way. Check your spam folder too.",
    back: "Back to sign in",
    verifiedSignIn: "Email confirmed. Sign in with your authenticator code.",
    forgotLink: "Forgot password?",
    forgotTitle: "Reset your password",
    forgotSubtitle: "Enter your account email and we will send a reset code.",
    forgotSubmit: "Send code",
    resetSubtitle: "If an account exists for {email}, we have sent it a code.",
    newPassword: "New password",
    resetSubmit: "Change password",
    resetDone: "Password changed. Sign in with your new password.",
  },
  uz: {
    title: "UZ Stock Analyzer'ga kirish",
    subtitle: "Tadqiqotlaringiz va kuzatuv ro'yxatlaringiz kirgandan so'ng sinxronlanadi.",
    registerTitle: "Akkaunt yaratish",
    registerSubtitle: "Tadqiqotlar, kompaniyalar va qaydlarni bitta ish maydonida saqlang.",
    remember: "Meni eslab qolish",
    showPassword: "Parolni ko'rsatish",
    hidePassword: "Parolni yashirish",
    google: "Google orqali davom etish",
    divider: "yoki",
    market: "UZSE bozori",
    marketFallback: "O'zbekiston bozorining dolzarb ma'lumotlari",
    signedInTitle: "Akkaunt ulangan",
    signedInSubtitle: "Siz tizimga kirgansiz va shaxsiy ish maydoniga o'tishingiz mumkin.",
    openProfile: "Profilni ochish",
    privacy: "Kirish ma'lumotlari himoyalangan va faqat akkauntingizga kirish uchun ishlatiladi.",
    verifyTitle: "Emailni tasdiqlang",
    verifySubtitle: "{email} manziliga 6 xonali kod yubordik. Kirishni yakunlash uchun uni kiriting.",
    codeLabel: "Xatdagi kod",
    verifySubmit: "Tasdiqlash",
    resend: "Kodni qayta yuborish",
    resendIn: "{seconds} soniyadan keyin qayta yuborish",
    resent: "Yangi kod yuborildi. «Spam» jildini ham tekshiring.",
    back: "Kirishga qaytish",
    verifiedSignIn: "Email tasdiqlandi. Autentifikator kodi bilan kiring.",
    forgotLink: "Parolni unutdingizmi?",
    forgotTitle: "Parolni tiklash",
    forgotSubtitle: "Akkaunt emailini kiriting — parolni tiklash kodini yuboramiz.",
    forgotSubmit: "Kod yuborish",
    resetSubtitle: "Agar {email} manzili bilan akkaunt mavjud bo'lsa, unga kod yubordik.",
    newPassword: "Yangi parol",
    resetSubmit: "Parolni o'zgartirish",
    resetDone: "Parol o'zgartirildi. Yangi parol bilan kiring.",
  },
};

function authPageText(language) {
  return AUTH_PAGE_TEXTS[normalizeLanguage(language)] || AUTH_PAGE_TEXTS.ru;
}

export { authPageText };
