import { normalizeLanguage } from "./i18n.jsx";

const MARKET_TEXTS = {
  ru: {
    nav: "Рынок",
    title: "Цены акций UZSE",
    subtitle: "Актуальные цены, дневной диапазон и изменение к предыдущему закрытию",
    updated: "Обновлено",
    refresh: "Обновить",
    loading: "Загружаем котировки...",
    ready: "Котировки загружены",
    empty: "Нет данных по выбранному фильтру",
    search: "Поиск по тикеру или компании",
    all: "Все",
    stocks: "Акции",
    bonds: "Облигации",
    preferredStocks: "Привилегированные",
    ordinaryStocks: "Обыкновенные",
    bondOne: "облигация",
    instruments: "Инструментов",
    traded: "Сделки сегодня",
    advancers: "Рост",
    decliners: "Снижение",
    unchanged: "Без изменений",
    topGrowth: "Лидер роста",
    topDrop: "Лидер снижения",
    tableTitle: "Биржевые инструменты",
    showing: "Показано",
    ticker: "Тикер",
    company: "Компания",
    last: "Последняя",
    change: "Изм.",
    open: "Открытие",
    high: "Макс.",
    low: "Мин.",
    date: "Дата сделки",
    closeDate: "закр.",
    type: "Тип",
    ordinary: "обыкновенный",
    preferred: "привилегированный",
    source: "UZSE",
    analyze: "Анализ",
    noTrade: "нет сделки",
    volume: "Объём торгов",
    marketCap: "Капитализация",
    volumeCol: "Объём",
    tradeCount: "сделок",
    volQty: "Объём (шт)",
    nominalCol: "Номинал",
    nominalToPrice: "Цена / номинал",
    avgSharePrice: "Ср. цена акции",
    avgTradePrice: "Ср. сумма сделки",
    volShare: "% объёма",
    bigTrade: "Крупнейшая сделка",
    tradeQtyUnit: "шт",
    grpOverview: "Обзор AI-скринер",
    grpVolumes: "Объёмы",
    grpFinancials: "Фин. показатели",
    grpMultiples: "Мультипликаторы",
    grpRatios: "Коэффициенты",
    currentRatio: "Текущая ликвидность",
    quickRatio: "Быстрая ликвидность",
    debtAssets: "Долг/Активы",
    assetTurnover: "Оборачиваемость активов",
    mktCap: "Капитализация",
    netMargin: "Чистая маржа",
    netMarginBankNote: "для банков — от совокупного дохода",
    equityAssets: "Капитал/Активы",
    checkFlag: "проверить",
    estimateFlag: "оценка",
    debtEquity: "Долг/Капитал",
    exportCsv: "Экспорт CSV",
    topGainers: "Топ роста",
    topLosers: "Топ падения",
    topLiquidity: "Топ ликвидности",
    finRevenue: "Выручка",
    finGross: "Валовая прибыль",
    finCash: "Наличность в кассе",
    finLiab: "Общие обязательства",
    finNet: "Чистая прибыль",
    finOperating: "Операц. доход",
    isin: "ISIN",
    sector: "Сектор",
    shareType: "Тип бумаги",
    pe: "P/E",
    pb: "P/B",
    roe: "ROE, %",
    roa: "ROA, %",
    finPeriod: "Отчётный период",
    finCoverage: "Охват периода",
    csvTrades: "Сделок",
    csvTitle: "UZSE — рынок и отчётность эмитентов",
    csvGenerated: "Выгружено",
    csvSession: "Торговая сессия",
    csvPeriod: "Период",
    csvPeriodNote: "Открытие, макс., мин., объёмы, средние и крупнейшая сделка — за выбранный период (суммы сессий внутри него); капитализация и мультипликаторы — на сегодня.",
    csvFilter: "Фильтр",
    csvSort: "Сортировка",
    csvSortDefault: "по дате сделки, затем по модулю изменения",
    csvRows: "Строк",
    csvFav: "только избранное",
    csvSearch: "поиск",
    csvSources: "Котировки — UZSE (uzse.uz). Финансовая отчётность — раскрытия эмитентов (openinfo.uz). Капитализация, мультипликаторы и коэффициенты рассчитаны платформой.",
    csvMoneyNote: "Денежные величины — в сумах (UZS).",
  },
  en: {
    nav: "Market",
    title: "UZSE stock prices",
    subtitle: "Latest prices, daily range, and change versus previous close",
    updated: "Updated",
    refresh: "Refresh",
    loading: "Loading quotes...",
    ready: "Quotes loaded",
    empty: "No instruments for this filter",
    search: "Search ticker or company",
    all: "All",
    stocks: "Stocks",
    bonds: "Bonds",
    preferredStocks: "Preferred",
    ordinaryStocks: "Ordinary",
    bondOne: "bond",
    instruments: "Instruments",
    traded: "Traded today",
    advancers: "Up",
    decliners: "Down",
    unchanged: "Unchanged",
    topGrowth: "Top gainer",
    topDrop: "Top decliner",
    tableTitle: "Market instruments",
    showing: "Showing",
    ticker: "Ticker",
    company: "Company",
    last: "Last",
    change: "Chg.",
    open: "Open",
    high: "High",
    low: "Low",
    date: "Trade date",
    closeDate: "close",
    type: "Type",
    ordinary: "ordinary share",
    preferred: "preferred share",
    source: "UZSE",
    analyze: "Analyze",
    noTrade: "no trade",
    volume: "Volume",
    marketCap: "Market cap",
    volumeCol: "Volume",
    tradeCount: "trades",
    volQty: "Volume (units)",
    nominalCol: "Par value",
    nominalToPrice: "Price / par",
    avgSharePrice: "Avg share price",
    avgTradePrice: "Avg trade size",
    volShare: "% of volume",
    bigTrade: "Largest trade",
    tradeQtyUnit: "units",
    grpOverview: "AI screener overview",
    grpVolumes: "Volumes",
    grpFinancials: "Financials",
    grpMultiples: "Multiples",
    grpRatios: "Key ratios",
    currentRatio: "Current ratio",
    quickRatio: "Quick ratio",
    debtAssets: "Debt/Assets",
    assetTurnover: "Asset turnover",
    mktCap: "Market cap",
    netMargin: "Net margin",
    netMarginBankNote: "banks: over total income",
    equityAssets: "Equity/Assets",
    checkFlag: "check",
    estimateFlag: "estimate",
    debtEquity: "Debt/Equity",
    exportCsv: "Export CSV",
    topGainers: "Top gainers",
    topLosers: "Top losers",
    topLiquidity: "Top liquidity",
    finRevenue: "Revenue",
    finGross: "Gross profit",
    finCash: "Cash on hand",
    finLiab: "Total liabilities",
    finNet: "Net profit",
    finOperating: "Operating income",
    isin: "ISIN",
    sector: "Sector",
    shareType: "Security type",
    pe: "P/E",
    pb: "P/B",
    roe: "ROE, %",
    roa: "ROA, %",
    finPeriod: "Reporting period",
    finCoverage: "Period coverage",
    csvTrades: "Trades",
    csvTitle: "UZSE — market and issuer reporting",
    csvGenerated: "Exported",
    csvSession: "Trading session",
    csvPeriod: "Period",
    csvPeriodNote: "Open, high, low, volumes, averages and the largest trade cover the selected period (its sessions summed); market cap and multiples are as of today.",
    csvFilter: "Filter",
    csvSort: "Sorted by",
    csvSortDefault: "trade date, then absolute change",
    csvRows: "Rows",
    csvFav: "favorites only",
    csvSearch: "search",
    csvSources: "Quotes — UZSE (uzse.uz). Financial statements — issuer filings (openinfo.uz). Market cap, multiples and ratios are computed by the platform.",
    csvMoneyNote: "Monetary figures are in soum (UZS).",
  },
  uz: {
    nav: "Bozor",
    title: "UZSE aksiya narxlari",
    subtitle: "So'nggi narxlar, kunlik oraliq va oldingi yopilish bilan farq",
    updated: "Yangilandi",
    refresh: "Yangilash",
    loading: "Kotirovkalar yuklanmoqda...",
    ready: "Kotirovkalar yuklandi",
    empty: "Bu filtr bo'yicha ma'lumot yo'q",
    search: "Ticker yoki kompaniya bo'yicha qidirish",
    all: "Hammasi",
    stocks: "Aksiyalar",
    bonds: "Obligatsiyalar",
    preferredStocks: "Imtiyozli",
    ordinaryStocks: "Oddiy",
    bondOne: "obligatsiya",
    instruments: "Instrumentlar",
    traded: "Bugun savdo bo'lgan",
    advancers: "O'sish",
    decliners: "Pasayish",
    unchanged: "O'zgarishsiz",
    topGrowth: "Eng katta o'sish",
    topDrop: "Eng katta pasayish",
    tableTitle: "Bozor instrumentlari",
    showing: "Ko'rsatilgan",
    ticker: "Ticker",
    company: "Kompaniya",
    last: "So'nggi",
    change: "O'zg.",
    open: "Ochilish",
    high: "Maks.",
    low: "Min.",
    date: "Savdo sanasi",
    closeDate: "yop.",
    type: "Tur",
    ordinary: "oddiy aksiya",
    preferred: "imtiyozli aksiya",
    source: "UZSE",
    analyze: "Tahlil",
    noTrade: "savdo yo'q",
    volume: "Savdo hajmi",
    marketCap: "Kapitalizatsiya",
    volumeCol: "Hajm",
    tradeCount: "savdo",
    volQty: "Hajm (dona)",
    nominalCol: "Nominal",
    nominalToPrice: "Narx / nominal",
    avgSharePrice: "O'rt. aksiya narxi",
    avgTradePrice: "O'rt. bitim summasi",
    volShare: "Hajm %",
    bigTrade: "Eng katta bitim",
    tradeQtyUnit: "dona",
    grpOverview: "AI-skrener sharhi",
    grpVolumes: "Hajmlar",
    grpFinancials: "Moliyaviy ko'rsatkichlar",
    grpMultiples: "Multiplikatorlar",
    grpRatios: "Koeffitsiyentlar",
    currentRatio: "Joriy likvidlik",
    quickRatio: "Tez likvidlik",
    debtAssets: "Qarz/Aktivlar",
    assetTurnover: "Aktivlar aylanmasi",
    mktCap: "Kapitalizatsiya",
    netMargin: "Sof marja",
    netMarginBankNote: "banklar uchun — jami daromaddan",
    equityAssets: "Kapital/Aktivlar",
    checkFlag: "tekshirish",
    estimateFlag: "baholash",
    debtEquity: "Qarz/Kapital",
    exportCsv: "CSV eksport",
    topGainers: "Eng ko'p o'sganlar",
    topLosers: "Eng ko'p tushganlar",
    topLiquidity: "Eng likvidlar",
    finRevenue: "Tushum",
    finGross: "Yalpi foyda",
    finCash: "Kassadagi naqd",
    finLiab: "Jami majburiyatlar",
    finNet: "Sof foyda",
    finOperating: "Operatsion daromad",
    isin: "ISIN",
    sector: "Sektor",
    shareType: "Qogʻoz turi",
    pe: "P/E",
    pb: "P/B",
    roe: "ROE, %",
    roa: "ROA, %",
    finPeriod: "Hisobot davri",
    finCoverage: "Davr qamrovi",
    csvTrades: "Bitimlar",
    csvTitle: "UZSE — bozor va emitentlar hisoboti",
    csvGenerated: "Yuklab olingan",
    csvSession: "Savdo sessiyasi",
    csvPeriod: "Davr",
    csvPeriodNote: "Ochilish, maks., min., hajmlar, o'rtachalar va eng katta bitim — tanlangan davr uchun (uning sessiyalari yig'indisi); kapitalizatsiya va multiplikatorlar — bugungi holatga.",
    csvFilter: "Filtr",
    csvSort: "Saralash",
    csvSortDefault: "bitim sanasi, soʻng oʻzgarish moduli",
    csvRows: "Qatorlar",
    csvFav: "faqat tanlanganlar",
    csvSearch: "qidiruv",
    csvSources: "Kotirovkalar — UZSE (uzse.uz). Moliyaviy hisobot — emitentlar oshkor qilishi (openinfo.uz). Kapitalizatsiya, multiplikatorlar va koeffitsiyentlar platforma tomonidan hisoblangan.",
    csvMoneyNote: "Pul qiymatlari soʻmda (UZS).",
  },
};

const SECTOR_LABELS = {
  ru: {
    all: "Все",
    finance: "Финансы",
    funds: "Фонды",
    manufacturing: "Производство",
    mining: "Добыча",
    transport: "Транспорт",
    logistics: "Логистика",
    telecom: "Телеком",
    trade: "Торговля",
    professional: "Услуги",
    other: "Прочее",
  },
  en: {
    all: "All",
    finance: "Finance",
    funds: "Funds",
    manufacturing: "Manufacturing",
    mining: "Mining",
    transport: "Transport",
    logistics: "Logistics",
    telecom: "Telecom",
    trade: "Trade",
    professional: "Services",
    other: "Other",
  },
  uz: {
    all: "Hammasi",
    finance: "Moliya",
    funds: "Fondlar",
    manufacturing: "Ishlab chiqarish",
    mining: "Konchilik",
    transport: "Transport",
    logistics: "Logistika",
    telecom: "Telekom",
    trade: "Savdo",
    professional: "Xizmatlar",
    other: "Boshqalar",
  },
};

function sectorLabel(language, sector) {
  const lang = normalizeLanguage(language);
  return SECTOR_LABELS[lang]?.[sector] ?? SECTOR_LABELS.ru[sector] ?? sector;
}

function mt(language, key) {
  const lang = normalizeLanguage(language);
  return MARKET_TEXTS[lang]?.[key] ?? MARKET_TEXTS.ru[key] ?? key;
}

export { mt, sectorLabel };
