"""Render supplied financial and bank ratios with their stated units."""

from __future__ import annotations
from reporting.localization import _normalize_language
from reporting.presentation import _format_report_pct, _table_from_rows


def _ratio_article_table(
    metrics: dict,
    ifrs_snapshot: dict,
    language: str,
    bank_extra: dict | None = None,
) -> dict | None:
    lang = _normalize_language(language)
    headers = {
        "ru": ["Показатель", "Значение", "Ориентир / норма", "Оценка", "Смысл"],
        "en": ["Metric", "Value", "Benchmark", "Assessment", "Meaning"],
        "uz": ["Ko'rsatkich", "Qiymat", "Me'yor", "Baho", "Mazmuni"],
    }.get(lang, ["Показатель", "Значение", "Ориентир / норма", "Оценка", "Смысл"])
    metric_rows: list[list[str]] = []
    bank_extra = bank_extra or {}
    ratio_translations = {
        "en": {
            "Итоговый скоринг": "Overall score",
            "Сводная оценка качества отчётности": "Summary assessment of reporting quality",
            "LDR — Кредиты / Депозиты": "LDR — Loans / Deposits",
            "Текущая ликвидность": "Current liquidity",
            "Активы банка, размещённые в кредитах, vs. клиентская депозитная база": "Bank assets placed in loans vs. the client deposit base",
            "Способность покрывать краткосрочные обязательства": "Ability to cover short-term liabilities",
            "Ликвид. активы 1-й линии / Активы": "First-line liquid assets / Assets",
            "Касса + счёт в ЦБ / итого активов — мгновенная ликвидность": "Cash + Central Bank account / total assets — immediate liquidity",
            "ROA (аннуализ.)": "ROA, annualized",
            "Прибыль на активы": "Profit generated by assets",
            "ROE (аннуализ.)": "ROE, annualized",
            "Доходность собственного капитала": "Return on equity capital",
            "NIM — Чистая процентная маржа": "NIM — Net interest margin",
            "Чистый процентный доход / итого активов": "Net interest income / total assets",
            "Чистая маржа прибыли": "Net profit margin",
            "Сколько прибыли остаётся с дохода": "How much profit remains from income",
            "Резервы / Брутто-кредиты (текущий)": "Loss allowance / gross loans (current)",
            "Резервы / Брутто-кредиты (предыдущий)": "Loss allowance / gross loans (previous)",
            "Coverage ratio — покрытие кредитных потерь резервами": "Coverage ratio — loan losses covered by allowances",
            "Coverage ratio предыдущего периода для сравнения": "Previous-period coverage ratio for comparison",
            "Нагрузка резервирования": "Provision burden",
            "Резервы периода / процентные доходы — доля прибыли на покрытие потерь": "Period provisions / interest income — share of income used to cover losses",
            "Капитал / Активы (CAR упрощ.)": "Capital / Assets (simplified CAR)",
            "Собственный капитал к активам — приближённая достаточность": "Equity to assets — approximate capital adequacy",
            "Коэффициент задолженности (D/A)": "Debt ratio (D/A)",
            "Доля обязательств в активах": "Share of liabilities in assets",
            "D/E — Долг / Капитал": "D/E — Debt / Equity",
            "Финансовый рычаг": "Financial leverage",
            "Операционные расходы / чистый доход": "Operating expenses / net income",
            "Покрытие % расходов доходами": "Interest expense coverage by income",
            "Процентные доходы / процентные расходы": "Interest income / interest expense",
            "Доля непроц. доходов": "Non-interest income share",
            "Непроцентные доходы / совокупные доходы": "Non-interest income / total income",
            "Покрытие процентов": "Interest coverage",
            "Запас прибыли для выплаты процентов": "Profit buffer for interest payments",
            "Долг / капитал": "Debt / equity",
            "Во сколько раз долг соотносится с собственным капиталом": "How debt compares with equity capital",
        }
    }

    def tr_ratio(text: str) -> str:
        if lang == "ru":
            return text
        translated = (ratio_translations.get(lang) or {}).get(str(text))
        if translated:
            return translated
        if lang == "en":
            return (
                str(text)
                .replace("норм.", "normal")
                .replace("Норма", "Normal")
                .replace("банки", "banks")
                .replace("Базель", "Basel")
            )
        return text

    def tr_assessment(text: str) -> str:
        if lang == "ru" or text in (None, "", "—"):
            return text
        if lang == "en":
            return {
                "✓ Хорошо": "✓ Good",
                "~ Умеренно": "~ Moderate",
                "⚠ Высокий": "⚠ High",
                "⚠ Слабый": "⚠ Weak",
                "✓ Норма": "✓ Normal",
                "~ Вне нормы": "~ Outside normal range",
            }.get(str(text), tr_ratio(str(text)))
        return text

    def _assess(value, good_threshold, warn_threshold, *, reverse: bool = False, fmt: str = "pct") -> str:
        """Return assessment label based on value vs thresholds. reverse=True: lower is better."""
        if value is None:
            return "—"
        v = float(value)
        if reverse:
            if v <= good_threshold:
                return tr_assessment("✓ Хорошо")
            if v <= warn_threshold:
                return tr_assessment("~ Умеренно")
            return tr_assessment("⚠ Высокий")
        else:
            if v >= good_threshold:
                return tr_assessment("✓ Хорошо")
            if v >= warn_threshold:
                return tr_assessment("~ Умеренно")
            return tr_assessment("⚠ Слабый")

    def add(
        label: str,
        value,
        meaning: str,
        benchmark: str = "—",
        assessment: str = "—",
        *,
        pct: bool = False,
        ratio_suffix: str = "",
        digits: int = 2,
    ):
        if value is None or value == "":
            return
        if pct:
            formatted = _format_report_pct(value, language, digits=digits)
        elif ratio_suffix:
            formatted = f"{round(float(value), digits)}{ratio_suffix}"
        else:
            formatted = str(value)
        metric_rows.append([tr_ratio(label), formatted, tr_ratio(benchmark), tr_assessment(assessment), tr_ratio(meaning)])

    quality = (ifrs_snapshot or {}).get("quality") or {}
    balance = (ifrs_snapshot or {}).get("balance_sheet") or {}
    income = (ifrs_snapshot or {}).get("income_statement") or {}
    bank = (ifrs_snapshot or {}).get("bank") or {}
    is_bank = bool(bank.get("is_bank"))

    # ── Scoring ────────────────────────────────────────────────────────────
    # Composite "Итоговый скоринг" row removed for ТЗ compliance (2026-07-09):
    # a single attractiveness grade reads as a forbidden «балл привлекательности».
    # The underlying factual metrics below are kept and shown on their own.

    # ── Liquidity ──────────────────────────────────────────────────────────
    ldr = bank.get("ldr_pct")
    add(
        "LDR — Кредиты / Депозиты" if is_bank else "Текущая ликвидность",
        ldr if is_bank else balance.get("current_ratio"),
        "Активы банка, размещённые в кредитах, vs. клиентская депозитная база" if is_bank else "Способность покрывать краткосрочные обязательства",
        benchmark="< 100%" if is_bank else "1,5–2,5",
        assessment=_assess(ldr, 100, 120, reverse=True) if is_bank else _assess(balance.get("current_ratio"), 1.5, 1.0),
        pct=is_bank,
    )
    first_line = bank_extra.get("first_line_liquidity_pct")
    add(
        "Ликвид. активы 1-й линии / Активы",
        first_line,
        "Касса + счёт в ЦБ / итого активов — мгновенная ликвидность",
        benchmark="> 5%",
        assessment=_assess(first_line, 8, 4),
        pct=True,
    )
    if not is_bank:
        add("Текущая ликвидность", balance.get("current_ratio"), "Способность покрывать краткосрочные обязательства", benchmark="1,5–2,5")

    # ── Profitability ──────────────────────────────────────────────────────
    roe = quality.get("roe_pct") or (bank.get("roe_pct") if is_bank else None)
    roa = quality.get("roa_pct") or (bank.get("roa_pct") if is_bank else None)
    nim = bank.get("nim_pct")
    add(
        "ROA (аннуализ.)" if is_bank else "ROA",
        roa,
        "Прибыль на активы",
        benchmark="1–2% (норм.)" if is_bank else "> 5%",
        assessment=_assess(roa, 1, 0.5),
        pct=True,
    )
    add(
        "ROE (аннуализ.)" if is_bank else "ROE",
        roe,
        "Доходность собственного капитала",
        benchmark="10–20% (норм.)",
        assessment=_assess(roe, 10, 5),
        pct=True,
    )
    if is_bank and nim is not None:
        add("NIM — Чистая процентная маржа", nim, "Чистый процентный доход / итого активов", benchmark="3–5% (норм.)", assessment=_assess(nim, 3, 1), pct=True)
    add(
        "Чистая маржа прибыли",
        income.get("net_margin_pct"),
        "Сколько прибыли остаётся с дохода",
        benchmark="15–25%",
        assessment=_assess(income.get("net_margin_pct"), 15, 5),
        pct=True,
    )

    # ── Asset quality (bank-specific) ──────────────────────────────────────
    cov_cur = bank_extra.get("coverage_ratio_current_pct")
    cov_prior = bank_extra.get("coverage_ratio_prior_pct")
    res_burden = bank_extra.get("reserve_burden_pct")
    if is_bank:
        add(
            "Резервы / Брутто-кредиты (текущий)",
            cov_cur,
            "Coverage ratio — покрытие кредитных потерь резервами",
            benchmark="< 2%",
            assessment=_assess(cov_cur, 2, 3, reverse=True) if cov_cur is not None else "—",
            pct=True,
        )
        add(
            "Резервы / Брутто-кредиты (предыдущий)",
            cov_prior,
            "Coverage ratio предыдущего периода для сравнения",
            benchmark="< 2%",
            assessment=_assess(cov_prior, 2, 3, reverse=True) if cov_prior is not None else "—",
            pct=True,
        )
        add(
            "Нагрузка резервирования",
            res_burden,
            "Резервы периода / процентные доходы — доля прибыли на покрытие потерь",
            benchmark="< 10%",
            assessment=_assess(res_burden, 10, 15, reverse=True) if res_burden is not None else "—",
            pct=True,
        )

    # ── Capital adequacy ───────────────────────────────────────────────────
    car = bank.get("car_simple_pct")
    if is_bank and car is not None:
        add("Капитал / Активы (CAR упрощ.)", car, "Собственный капитал к активам — приближённая достаточность", benchmark="> 8% (Базель)", assessment=_assess(car, 10, 6), pct=True)
    d_to_e = balance.get("debt_to_equity")
    d_to_a_raw = balance.get("debt_to_assets")
    d_to_a = (d_to_a_raw or 0) * 100 if d_to_a_raw is not None else None
    add(
        "Коэффициент задолженности (D/A)",
        d_to_a,
        "Доля обязательств в активах",
        benchmark="~85% (норм. для банков)" if is_bank else "< 50%",
        assessment="✓ Норма" if (is_bank and d_to_a is not None and 80 <= d_to_a <= 90) else _assess(d_to_a, 50, 70, reverse=True) if not is_bank else "—",
        pct=True,
    )
    add(
        "D/E — Долг / Капитал",
        d_to_e,
        "Финансовый рычаг",
        benchmark="4–8× (банки)" if is_bank else "< 1,5",
        assessment="✓ Норма" if (is_bank and d_to_e is not None and 4 <= d_to_e <= 8) else _assess(d_to_e, 1.5, 2.0, reverse=True) if not is_bank else "—",
    )

    # ── Operational efficiency ─────────────────────────────────────────────
    cir = bank.get("cir_pct")
    int_cov = bank.get("interest_income_coverage") or bank_extra.get("interest_income_coverage")
    non_int_share = bank_extra.get("non_interest_share_pct")
    if is_bank:
        add("CIR — Cost-to-Income", cir, "Операционные расходы / чистый доход", benchmark="40–60%", assessment=_assess(cir, 60, 70, reverse=True) if cir is not None else "—", pct=True)
        add(
            "Покрытие % расходов доходами",
            int_cov,
            "Процентные доходы / процентные расходы",
            benchmark="> 1,2×",
            assessment=_assess(int_cov, 1.5, 1.2) if int_cov is not None else "—",
            ratio_suffix="×",
        )
        add(
            "Доля непроц. доходов",
            non_int_share,
            "Непроцентные доходы / совокупные доходы",
            benchmark="20–40%",
            assessment="✓ Норма" if (non_int_share is not None and 20 <= non_int_share <= 40) else "~ Вне нормы" if non_int_share is not None else "—",
            pct=True,
        )
    else:
        add("Покрытие процентов", quality.get("interest_coverage"), "Запас прибыли для выплаты процентов", benchmark="> 3×")
        add("Долг / капитал", d_to_e, "Во сколько раз долг соотносится с собственным капиталом", benchmark="< 1,5")

    return _table_from_rows(
        "ratio_summary",
        {
            "ru": "Таблица 7 — Сводный коэффициентный профиль",
            "en": "Table 7 — Ratio summary profile",
            "uz": "Jadval 7 — Koeffitsiyentlar profili",
        }.get(lang, "Таблица 7 — Сводный коэффициентный профиль"),
        headers,
        metric_rows,
        source="metrics.ifrs_snapshot",
    )
